### PR TITLE
Refactor server

### PR DESCRIPTION
**Pull request by EnoF**
Refactored server side code. Introduced `serverHelper` to handle the common handlers:

* createAndReturnId
* deleteById
* getAll
* getById
* sendAndResolve
* updateById
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/Jumio/con-rest/pull/65%23issuecomment-70981746%22%2C%20%22https%3A//github.com/Jumio/con-rest/pull/65%23issuecomment-71013458%22%2C%20%22https%3A//github.com/Jumio/con-rest/pull/65%23issuecomment-71020336%22%2C%20%22https%3A//github.com/Jumio/con-rest/pull/65%23issuecomment-71020352%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/Jumio/con-rest/pull/65%23issuecomment-70981746%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22rebased%20with%20latest%20master%22%2C%20%22created_at%22%3A%20%222015-01-22T07%3A33%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1508400%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EnoF%22%7D%7D%2C%20%7B%22body%22%3A%20%22Issue%20%2367%20should%20be%20fixed%20before%20merging%20branch%20to%20master%20%22%2C%20%22created_at%22%3A%20%222015-01-22T12%3A28%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T13%3A33%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T13%3A34%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/TheBay0r%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/TheBay0r'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/Jumio/con-rest/pull/65#issuecomment-70981746'>General Comment</a></b>
- <a href='https://github.com/EnoF'></a> rebased with latest master
- <a href='https://github.com/TheBay0r'></a> Issue #67 should be fixed before merging branch to master

<a href='https://www.codereviewhub.com/Jumio/con-rest/pull/65?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Jumio/con-rest/pull/65?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Jumio/con-rest/pull/65?approve=0'></a>&nbsp;<a href='https://github.com/Jumio/con-rest/pull/65'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by EnoF** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/Jumio/con-rest/pull/65'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by EnoF** [comment]
rebased with latest master

**Comment by TheBay0r** [comment]
Issue #67 should be fixed before merging branch to master

**Comment by TheBay0r** [comment]
:+1:

**Comment by TheBay0r** [comment]
:shipit:

**Pull request merged**
